# Generated by Django 2.2.16 on 2022-08-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220804_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
